### ISSUE TITLE
RuntimeError: This model contains ops not capturable by Pytorch/XLA: aten::nonzero=6 __

### ISSUE THREAD

**Issue by kukugpt** [google-ai-edge/ai-edge-torch#103]
### Description of the bug:

When I convert object detection with nms ops and filter ops， has below error：
RuntimeError: This model contains ops not capturable by Pytorch/XLA: aten::nonzero=6

**Comment by pkgoogle** [comment]
Hi @kukugpt, would you happen to know your object detection model's name? or do you have a reproducible script/simple model that reproduces this? Thanks for your help.
