### ISSUE TITLE
how to remove transpose op

### ISSUE THREAD

**Issue by kukugpt** [google-ai-edge/ai-edge-torch#111]
### Description of the bug:

Because the default channel of torch is [n,3,h, w], tf is[n,h,w,3],so the covnerted model has a tranpose op,how to remove it and the input channel is [n,h,w,3]

**Comment by pkgoogle** [comment]
Hi @kukugpt, if you want to achieve that, I believe it'll be easiest to just convert from TensorFlow instead of using AI-Edge-Torch. You can find some help here: https://www.tensorflow.org/lite/models/convert/convert_models#convert_a_keras_model_ . Is there any issue from doing this instead?

**Comment by chunnienc** [comment]
Hi @kukugpt , we provide a helper function `ai_edge_torch.to_channel_last_io` for changing the model inputs/outputs' channel order. Please refer to [the guide here](https://github.com/google-ai-edge/ai-edge-torch/blob/main/docs/pytorch_converter/README.md#convert-model-with-nhwc-channel-last-inputsoutputs). Our converter would do optimizations and remove transposes with best efforts afterwards.
