### ISSUE TITLE
AttributeError: type object 'ModelType' has no attribute 'PYTORCH'

### ISSUE THREAD

**Issue by kabyanil** [google-ai-edge/ai-edge-torch#114]
### Description of the bug:

I'm trying to convert a pytorch transformer model to tflite. I installed the package with 
```
pip install ai-edge-torch
```

I didn't have torch-xla installed, so I did
```
pip install torch-xla
```

Now, here is my model conversion code -

```
# 1. src_embed
import ai_edge_torch

sample_input = (torch.tensor([[ 0, 16, 21, 30, 21, 22, 21, 26, 15,  1,  2,  2,  2,  2,  2,  2,  2,  2, 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2]], dtype=torch.int32),)

edge_model = ai_edge_torch.convert(model.src_embed, sample_input)
```

I get the following error -
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-27-28f3e04fb2ae>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 
---> 10 edge_model = ai_edge_torch.convert(model.src_embed, sample_input)

3 frames
[/usr/local/lib/python3.10/dist-packages/ai_edge_torch/convert/conversion_utils.py](https://localhost:8080/#) in convert_stablehlo_to_tflite(shlo_graph_module, signatures, quant_config, _tfl_converter_flags)
    320 
    321     converter = tf.lite.TFLiteConverter.from_saved_model(temp_dir_path)
--> 322     converter._set_original_model_type(conversion_metadata_fb.ModelType.PYTORCH)
    323     converter._experimental_enable_composite_direct_lowering = True
    324 

AttributeError: type object 'ModelType' has no attribute 'PYTORCH'
```

### Actual vs expected behavior:

It is expected to convert the model successfully from pytorch to tflite. Whereas, I am getting an error.

**Comment by pkgoogle** [comment]
Hi @kabyanil, which transformer model are you trying to convert? For custom LLMs the preferred way is to use our generative API: https://developers.googleblog.com/en/ai-edge-torch-generative-api-for-custom-llms-on-device/ Let me know if that works for you or if you are trying to do something else.

**Comment by kabyanil** [comment]
I have converting a custom coded transformer model for translation. Everything is built up from scratch.

**Comment by pkgoogle** [comment]
Hi @kabyanil, can you please share your model? Or possibly a simpler model which reproduces this issue? Thanks.

**Comment by kabyanil** [comment]
I found an workaround to solve the issue. I used nobuco to convert my pytorch model to keras, then to tflite using

```
keras_model = nobuco.pytorch_to_keras(
    pytorch_model,
    args=[sample_input], kwargs=None,
    inputs_channel_order=ChannelOrder.PYTORCH,
    outputs_channel_order=ChannelOrder.PYTORCH
)


converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
tflite_model = converter.convert()
```
Hope this helps someone facing similar issues.

**Comment by johndpope** [comment]
seeing same issue - tensorflow==2.15

https://github.com/johndpope/IMF/blob/main/tf-export-edge.py


![image](https://github.com/user-attachments/assets/3991bc17-f05e-4885-aab3-d6230f434413)


code /home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/ai_edge_torch/convert/conversion_utils.py


![Screenshot from 2024-10-19 06-55-27](https://github.com/user-attachments/assets/143529cd-423e-47eb-9936-04ce9e5db325)

bumping to tensorflow=2.17 resolved things..
