### ISSUE TITLE
TransposeConv not merged with batchnorm2d

### ISSUE THREAD

**Issue by ZORO-Q** [google-ai-edge/ai-edge-torch#122]
### Description of the bug:

When I use ai-edge-torch convert pytorch model to tflite, the conv op was merged with batchnorm and the transposeconv was not merged with batchnorm

### Actual vs expected behavior:

how to keep their behavior consistant?

**Comment by pkgoogle** [comment]
Hi @ZORO-Q, do you have an example conversion script/model which shows/exhibit this behavior?

**Comment by ZORO-Q** [comment]
> Hi @ZORO-Q, do you have an example conversion script/model which shows/exhibit this behavior?
The model is a CRN model, which the decoder block is  consist of TransposeConv, batchnorm2d, Relu
![image](https://github.com/user-attachments/assets/5001e91b-573b-425f-8184-795954056672)

**Comment by ZORO-Q** [comment]
> Hello @ZORO-Q, I was expecting more code, less diagram.... can you share your code or maybe just the piece that exhibits this behavior? Thanks.

the code is
`encoder block = nn.Sequential(nn.Conv2d(in_channels=2,out_channels=2, kernel_size=(2, 5), stride=[1,2],padding=[0,2], groups=2), nn.Conv2d(in_channels=2,out_channels=16, kernel_size=(1,1), stride=[1,1],padding=[0,0], groups=1, nn.Batchnorm2d(16),nn.ReLU())
decoder_block = nn.Sequential(nn.ConvTranspose2d(in_channels=16,out_channels=16, kernel_size=(2, 5), stride=[1,2],padding=[0,2], groups=16), nn.Conv2d(in_channels=16,out_channels=1, kernel_size=(1,1), stride=[1,1],padding=[0,0], groups=1, nn.Batchnorm2d(16)) `

**Comment by pkgoogle** [comment]
Hi @ZORO-Q, thanks for the additional information ... I wasn't able to replicate since i think things have changed since you last tried it out ... what version/commit of AI-Edge-Torch did you test this against? ...

Here's the program I tried and the error I'm running into:

```py
import ai_edge_torch

import torch
from torch import nn


class TestModel(nn.Module):
    def __init__(self):
        super(TestModel, self).__init__()

        self.encoder_block = nn.Sequential(  
            nn.Conv2d(in_channels=2,out_channels=2, kernel_size=(2, 5), stride=[1,2],padding=[0,2], groups=2), 
            nn.Conv2d(in_channels=2,out_channels=16, kernel_size=(1,1), stride=[1,1],padding=[0,0], groups=1),  
            nn.BatchNorm2d(16),nn.ReLU()
        )

        self.decoder_block = nn.Sequential(  
            nn.ConvTranspose2d(in_channels=16,out_channels=16, kernel_size=(2, 5), stride=[1,2],padding=[0,2], groups=16),   
            nn.Conv2d(in_channels=16,out_channels=1, kernel_size=(1,1), stride=[1,1],padding=[0,0], groups=1),   
            nn.BatchNorm2d(1)
        )

    def forward(self, x):
        x = self.encoder_block(x)
        x = self.decoder_block(x)
        return x


sample_input = (torch.randn(1, 2, 224, 224),)
model = TestModel()

edge_model = ai_edge_torch.convert(model.eval(), sample_input)
edge_model.export("test_model.tflite")
```

```sh
raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: <unknown>:0: error: loc(callsite(callsite(callsite("__main__.TestModel/torch.nn.modules.container.Sequential_decoder_block/torch.nn.modules.conv.ConvTranspose2d_0;" at fused["XlaCallModule:", "XlaCallModule@__inference_inner_91"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_129"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): failed to legalize operation 'mhlo.convolution' that was explicitly marked illegal
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: error: mhlo to TFLite legalization failed.

I0000 00:00:1724190851.346588 1406703 cpu_client.cc:470] TfrtCpuClient destroyed.
```

I have tried stable, nightly, locally against branch 0.2.0.
