### ISSUE TITLE
Dynamic slicing on data-dependent value is not supported

### ISSUE THREAD

**Issue by markiicheng** [google-ai-edge/ai-edge-torch#168]
### Description of the bug:

Hi,
we want to convert wenet from pytorch to TFLite, but got the error 

"torch._dynamo.exc.Unsupported: Dynamic slicing on data-dependent value is not supported"

after tracing the code, it seems the problem is below function

```
def reverse_pad_list(ys_pad: torch.Tensor,
                     ys_lens: torch.Tensor,
                     pad_value: float = -1.0) -> torch.Tensor:
    """Reverse padding for the list of tensors.

    Args:
        ys_pad (tensor): The padded tensor (B, Tokenmax).
        ys_lens (tensor): The lens of token seqs (B)
        pad_value (int): Value for padding.

    Returns:
        Tensor: Padded tensor (B, Tokenmax).

    Examples:
        >>> x
        tensor([[1, 2, 3, 4], [5, 6, 7, 0], [8, 9, 0, 0]])
        >>> pad_list(x, 0)
        tensor([[4, 3, 2, 1],
                [7, 6, 5, 0],
                [9, 8, 0, 0]])

    """
    r_ys_pad = pad_sequence([(torch.flip(y.int()[:i], [0]))
                             for y, i in zip(ys_pad, ys_lens)], True,
                            pad_value)
    return r_ys_pad
```

can you please help to give some advice~
thanks~

**Comment by pkgoogle** [comment]
Hi @markiicheng, hard to say what the most correct action is w/o some more context... I believe the offending code is `y.int()[:i]`, is there any way to make that slicing static rather than dependent on `i`? Otherwise I believe at root it is a PyTorch Export issue: https://pytorch.org/docs/stable/export.html. Can you try to export independent of AI-Edge-Torch? -- if the issue is still there, then I believe you need to create an issue there but I do believe if you can find a way to do static slicing, it will resolve your issue.

**Comment by markiicheng** [comment]
Hi @pkgoogle,

you can get more model info from https://github.com/wenet-e2e/wenet.git, it's an open source audio recognition model.
It can be exported to ONNX by PyTorch Export. (https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_cpu.py)

If this is the limization of ai-edge-torch, maybe we need to find another way. Because it is hard to ask user to modify their model  to meet the conversion tool's requirement.

Thanks~~

**Comment by pkgoogle** [comment]
It seems like torch.onnx is using a different code workflow than torch.export ... do you have the script which produced the original error? Something that loads the model module and calls `ai_edge_torch.convert(model.eval(), ...)` on it? That will be helpful, thanks.

**Comment by markiicheng** [comment]
please refer to the below~thanks~~
```
import os
import math
import torch
from torchsummary import summary
import torchvision
import ai_edge_torch
import tensorflow as tf
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

# ASR - wenet
model_path = "model_path"
input_shape = (1, 64, 80)
input1_shape = (1, 4, 187)

pytorch_model = torch.load(model_path)
sample_inputs = (torch.randn(input_shape), torch.tensor([1]), torch.randn(input1_shape), torch.tensor([1]),)

edge_model = ai_edge_torch.convert(pytorch_model.eval(), sample_inputs)
edge_model.export("edge_model.tflite")

```

**Comment by pkgoogle** [comment]
> please refer to the below~thanks~~
> 
> ```
> import os
> import math
> import torch
> from torchsummary import summary
> import torchvision
> import ai_edge_torch
> import tensorflow as tf
> import numpy as np
> import torch.nn as nn
> import torch.nn.functional as F
> 
> # ASR - wenet
> model_path = "model_path"
> input_shape = (1, 64, 80)
> input1_shape = (1, 4, 187)
> 
> pytorch_model = torch.load(model_path)
> sample_inputs = (torch.randn(input_shape), torch.tensor([1]), torch.randn(input1_shape), torch.tensor([1]),)
> 
> edge_model = ai_edge_torch.convert(pytorch_model.eval(), sample_inputs)
> edge_model.export("edge_model.tflite")
> ```

Thanks... where is the model_path? I'm not familiar with the "wenet" project... if i try to use it as in the github `wenet.load('chinese')`, It gives me a wenet model not a torch model. When I load it via code, is there a known location it saves everything to that I can load from? Or where can I find whatever is at model_path?

**Comment by markiicheng** [comment]
I think it's complicated to get the requirement from wenet github (model and needed files)
so I upload the all files to the google drive. you can download it and extract it to the same location of script, maybe it would work.

[](https://drive.google.com/file/d/1bWAkER-JvAlWABuQ_-D61PI3RxKQL90_/view?usp=sharing)

Thanks~

**Comment by pkgoogle** [comment]
Hi @markiicheng, thanks I was able to reproduce w/ your files. Using our find_culprits function it can be shown this is a torch exportable issue:

```py
import torch

from ai_edge_torch.debug import find_culprits


pt_model = torch.load("wenet_test.pt")

input_shape = (1, 64, 80)
input1_shape = (1, 4, 187)
sample_inputs = (torch.randn(input_shape), torch.tensor([1]), torch.randn(input1_shape), torch.tensor([1]),)

culprits = find_culprits(pt_model.eval(), sample_inputs)
culprit = next(culprits)
culprit.print_code()
```

More information can be found here: https://github.com/google-ai-edge/ai-edge-torch/blob/main/docs/pytorch_converter/README.md#debugging--reporting-errors

Output:
```sh
python find_culprit.py 
# a lot output, same stack trace that you are getting
  File "xxxxxxxx/miniconda3/envs/aet_main/lib/python3.11/site-packages/torch/_dynamo/variables/lists.py", line 634, in __init__
    unimplemented("Dynamic slicing on data-dependent value is not supported")
  File "xxxxxxxxx/miniconda3/envs/aet_main/lib/python3.11/site-packages/torch/_dynamo/exc.py", line 221, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: Dynamic slicing on data-dependent value is not supported

from user code:
   File "xxxxxxx/issues/ai-edge-torch/168/wenet/transformer/asr_model.py", line 111, in forward
    loss_att, acc_att = self._calc_att_loss(encoder_out, encoder_mask,
  File "xxxxxxxx/issues/ai-edge-torch/168/wenet/transformer/asr_model.py", line 147, in _calc_att_loss
    r_ys_pad = reverse_pad_list(ys_pad, ys_pad_lens, float(self.ignore_id))
  File "xxxxxx/issues/ai-edge-torch/168/wenet/utils/common.py", line 171, in reverse_pad_list
    r_ys_pad = pad_sequence([(torch.flip(y.int()[:i], [0]))
  File "xxxxxxx/issues/ai-edge-torch/168/wenet/utils/common.py", line 171, in <listcomp>
    r_ys_pad = pad_sequence([(torch.flip(y.int()[:i], [0]))

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxxxxxx/issues/ai-edge-torch/168/find_culprit.py", line 13, in <module>
    culprit = next(culprits)
              ^^^^^^^^^^^^^^
  File "xxxxxx/git/ai-edge-torch/ai_edge_torch/debug/culprit.py", line 485, in find_culprits
    for search_result in _search_model(
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/debug/culprit.py", line 389, in _search_model
    raise ValueError(
ValueError: Your model is not exportable by torch.export.export. Please modify your model to be torch-exportable first.
```

Can you please raise an issue with PyTorch? https://github.com/pytorch/pytorch/issues. If you have no more open items for this issue on our end, please feel free to close or ask any additional questions.

**Comment by markiicheng** [comment]
Hi @pkgoogle ,

understand, thanks for your help~~
