### ISSUE TITLE
Converted model numerically different from the original torch model

### ISSUE THREAD

**Issue by vmanoj1996** [google-ai-edge/ai-edge-torch#20]
I converted the torch model using,
`edge_model = ai_edge_torch.convert(model, sampleInput)`

The model is a CNN based encoder + decoder network that outputs an 128x128 image. 

**Original Pytorch model output**
![image](https://github.com/google-ai-edge/ai-edge-torch/assets/8917581/1d4e6fdc-32d0-4643-9645-5c3ef8cb92b6)

**Converted model output**
![image](https://github.com/google-ai-edge/ai-edge-torch/assets/8917581/482ade78-c9a3-49e0-afdf-4e89012fc3d5)

Any ideas what can be going wrong here?

**Comment by advaitjain** [comment]
Expectation is for tflite output to be within tolerance of the pytorch model ([validation step](https://github.com/google-ai-edge/ai-edge-torch/blob/5f60e646479d8007510bf5c5392bc46e8bca194f/docs/pytorch_converter/getting_started.ipynb) in the getting started Colab).

Can you share code that reproduces this behavior?

**Comment by vmanoj1996** [comment]
Sorry for the lack of response. I rewrote the network in tf2 and used a more direct pipeline for tflite conversion.
Not looking for a solution to this issue currently.

**Comment by pkgoogle** [comment]
Hi @vmanoj1996, we would really like to resolve this if possible, if you can share maybe not the exact model but something which reproduces this -- we will be happy to try this out. (Maybe something from torchvision?).
