### ISSUE TITLE
Pytorch model converted to tflite is significantly slower

### ISSUE THREAD

**Issue by lusinlu** [google-ai-edge/ai-edge-torch#211]
### Description of the bug:

Hi, we are trying to run pytorch model on android and following examples of image segmentation from [google_ai_edge](https://github.com/google-ai-edge/litert-samples). We noticed that when running with the default model in the example, which is deeplab v3 the inference is ~40ms, but when we are using pytorch model (with ~2mln parameters, which is significantly smaller than deeplab) converted to tflite, the inference is ~200ms.
For converting the model, we are using the simple code:
```
model = ModelSparce()
model.load_state_dict(torch.load(args.weights)['model'], strict=False)
model.eval()

batch = (torch.randn(1, 3, 288, 288),)

edge_model = ai_edge_torch.convert(model, batch)
edge_model.export("model_aiedge.tflite")
```

What possibly can be the issue here.

**Comment by pkgoogle** [comment]
Hi @lusinlu, thanks for reporting the issue. Can you let us know what hardware/environment you are using? Such as are you using a real device or an emulator? For either case, can you give us the specifications, for example: Pixel 8 Pro API 34 (Android 14.0 "UpsideDownCake") | arm 64. The more information, the better. Thanks.

**Comment by zengjie617789** [comment]
I meet the same problem and I donot know what to do besides waiting.

**Comment by pkgoogle** [comment]
Hi @zengjie617789, can you please create a new issue for your specific case with reproducible code, including how you are measuring the performance. Thanks.
