### ISSUE TITLE
Encountered 'Redefinition of symbol: gelu_decomp_27' issue while converting Qwen2 model to TFLite

### ISSUE THREAD

**Issue by tilfdev** [google-ai-edge/ai-edge-torch#235]
### Description of the bug:

We are using the ai_edge_torch library to convert the Qwen2-0.5 model into TFLite format. We have made the necessary modifications in our own fork, available (https://github.com/google-ai-edge/ai-edge-torch/compare/main...a8nova:ai-edge-torch:qwen2). However, during the conversion process, we encountered the following error: "redefinition of symbol named 'gelu_decomp_27'"  
@a8nova,  If you need any clarification.

The following is the full error displayed.
(https://github.com/user-attachments/assets/ca4ea156-376d-47f0-b196-ef090cc1de47)

**Comment by haozha111** [comment]
qq: are you using latest nightly version? you can try 
pip install ai-edge-torch-nightly==0.3.0.dev20240918

**Comment by protobird-git** [comment]
Now, Qwen 2.5. is added as an example which is converted to tflite successfully. https://github.com/google-ai-edge/ai-edge-torch/tree/main/ai_edge_torch/generative/examples/qwen

**Comment by gudgud96** [comment]
Faced the same "redefinition of symbol named 'gelu_decomp_xx'" error. The following versions fixed it for me (I suppose updating all to the latest nightlies will work):
```
tf_nightly==2.19.0.dev20241003
ai-edge-litert-nightly==1.0.1.dev20241002
ai-edge-quantizer-nightly==0.0.1.dev20240718
ai-edge-torch-nightly==0.3.0.dev20240918 
```

**Comment by tilfdev** [comment]
thank you @protobird-git @gudgud96 . We have been unblocked, feel free to close this issue
