### ISSUE TITLE
Phi3 conversion to tflite

### ISSUE THREAD

**Issue by a8nova** [google-ai-edge/ai-edge-torch#26]
### Description of the bug:

I wanted to convert phi3 to tflite, I started modifying phi2.py to apply the differences. In the Attention class of phi3, there is a combined projection layer [self.qkv_proj = nn.Linear(self.hidden_size, op_size, bias=False)](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/modeling_phi3.py#L326).

I have defined the TENSOR_NAMES for phi3 just like in phi2.py, I am having an issue with ModelLoader class in loader.py where it has:
```
  @dataclass
  class TensorNames:
    attn_query_proj: str
    attn_key_proj: str
    attn_value_proj: str
    attn_output_proj: str
    ...
```

Do i pass the `self.qkv_proj ` tensor to all 3 query, key and value to the data loader class?

Thanks!

**Comment by haozha111** [comment]
Thanks for reporting the issue! Yes as you mentioned, Phi-3 has an updated attention mechanism which is different from what the library provides as of today. Adding @hheydary to look into the issue (who is original author for the phi-2 example).

**Comment by hheydary** [comment]
Greetings,

We just added a new field to the loader class [attn_fused_qkv_proj](https://github.com/google-ai-edge/ai-edge-torch/blob/ffc6b9cf856ef40e0175c10759f96cc4322105c2/ai_edge_torch/generative/utilities/loader.py#L105). Please use that to load model parameters.

**Comment by a8nova** [comment]
Thank you for the quick fix @haozha111 @hheydary
