### ISSUE TITLE
Need tflite inference example for tiny llama in python

### ISSUE THREAD

**Issue by rajendra-ml** [google-ai-edge/ai-edge-torch#274]
I have converted tiny llama to tflite by running ai_edge_torch/generative/examples/tiny_llama/convert_to_tflite.py . Is there an example of how to run inference in python using the generated tflite model? Thanks in advance.

**Comment by pkgoogle** [comment]
Hi @rajendra-ml, Here's the documentation on how to run arbitrary .tflite files: https://ai.google.dev/edge/litert/inference#run-python let me know if you have any additional questions.

**Comment by rajendra-ml** [comment]
Thanks a lot, that helps. This issue can be closed now.

**Comment by rajendra-ml** [comment]
closed
