### ISSUE TITLE
Getting an error while generating quantized tiny llama model due to AI-edge-quantizer

### ISSUE THREAD

**Issue by pallaviNNT** [google-ai-edge/ai-edge-torch#286]
### Description of the bug:

AttributeError: module 'ai_edge_quantizer.qtyping' has no attribute 'ComputePrecision'

**Steps followed:**
Ran requirements.txt from AI-edge-torch repo
https://github.com/google-ai-edge/ai-edge-torch/blob/main/requirements.txt

Cloned the Ai-edge-torch

cd ai_edge_torch/generative/examples/tiny_llama

ran command "python3.10 convert_to_tflite.py"

**Error:**

AttributeError: module 'ai_edge_quantizer.qtyping' has no attribute 'ComputePrecision'

### Actual vs expected behavior:

Tflite model needs to be generated without any error

**Comment by pkgoogle** [comment]
Hi @pallaviNNT, I'm running into a different issue ... can you tell me what commit your local files are on? (you can do `git log` and copy the top commit hash). Also it's generally recommended to use a venv environment and just do `pip install ai-edge-torch` or `pip install ai-edge-torch-nightly`. This should install the requirements automatically.

**Comment by chienhuikuo** [comment]
Hi @pallaviNNT, I ran into the same issue before. 
My solution is to clone the latest [ai_edge_quantizer](https://github.com/google-ai-edge/ai-edge-quantizer/tree/main/ai_edge_quantizer) to replace the version installed via pip, just for your reference. Hope it helps you!

**Comment by johndpope** [comment]
this should fix it too 
`pip install git+https://github.com/google-ai-edge/ai-edge-quantizer`
