### ISSUE TITLE
failed to convert 'SmolLM-135M' model to tflite. Error: 'tensorflow.lite.tools.flatbuffer_utils' has no attribute 'read_model_from_bytearray' 

### ISSUE THREAD

**Issue by merronmuche** [google-ai-edge/ai-edge-torch#313]
### Description of the bug:

we were trying to convert the SmolLM-135M model on Google Colab. During the conversion process, we encountered the following error:
AttributeError: module 'tensorflow.lite.tools.flatbuffer_utils' has no attribute 'read_model_from_bytearray'

here is the full error message :
[smollm.txt](https://github.com/user-attachments/files/17487387/smollm.txt)

### Actual vs expected behavior:

Actual: An attribute error was counted during the conversion process.
Expected: The model should have been successfully converted without this error.

**Comment by pkgoogle** [comment]
Hi @merronmuchem, can you provide a gist of what you are doing? (Save the colab copy as a gist).
