### ISSUE TITLE
how to do inference in quantization model

### ISSUE THREAD

**Issue by shubhamgupto** [google-ai-edge/ai-edge-torch#336]
### Description of the bug:

```
{
	"name": "ValueError",
	"message": "num_scales must be 1 for per-layer quantization, or 1 for per-axis quantization, but got 24.Tensor 97 has invalid quantization parameters.",
	"stack": "---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 interpreter = Interpreter(model_path=model_path)
      2 interpreter.allocate_tensors()
      4 # STEP 3: Get input and output tensors.

File ~/miniconda3/envs/dav2/lib/python3.11/site-packages/ai_edge_litert/interpreter.py:470, in Interpreter.__init__(self, model_path, model_content, experimental_delegates, num_threads, experimental_op_resolver_type, experimental_preserve_all_tensors, experimental_disable_delegate_clustering, experimental_default_delegate_latest_features)
    464 custom_op_registerers_by_name = [
    465     x for x in self._custom_op_registerers if isinstance(x, str)
    466 ]
    467 custom_op_registerers_by_func = [
    468     x for x in self._custom_op_registerers if not isinstance(x, str)
    469 ]
--> 470 self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
    471     model_path,
    472     op_resolver_id,
    473     custom_op_registerers_by_name,
    474     custom_op_registerers_by_func,
    475     experimental_preserve_all_tensors,
    476     experimental_disable_delegate_clustering,
    477     int(num_threads or 1),
    478     experimental_default_delegate_latest_features,
    479 )
    480 if not self._interpreter:
    481   raise ValueError('Failed to open {}'.format(model_path))

ValueError: num_scales must be 1 for per-layer quantization, or 1 for per-axis quantization, but got 24.Tensor 97 has invalid quantization parameters."
}
```

code - https://github.com/google-ai-edge/ai-edge-torch/blob/main/docs/pytorch_converter/README.md#quantization

### Any other information you'd like to share?

unable to use quantized model

**Comment by shubhamgupto** [comment]
i noticed if i set `is_per_channel=False, is_dynamic=False`, it works as expected

**Comment by pkgoogle** [comment]
Hi @shubhamgupto, the linked code doesn't define `torch_model`, what torch_model are you using?

**Comment by shubhamgupto** [comment]
> Hi @shubhamgupto, the linked code doesn't define `torch_model`, what torch_model are you using?

here is the repository - https://github.com/verlab/accelerated_features/tree/main

**Comment by pkgoogle** [comment]
Hi @shubhamgupto, It looks like you're inferencing... were you able to convert successfully? I actually couldn't convert:

my code:
```py
import torch
from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
from torch._export import capture_pre_autograd_graph

import ai_edge_torch
from ai_edge_torch.quantize.pt2e_quantizer import get_symmetric_quantization_config
from ai_edge_torch.quantize.pt2e_quantizer import PT2EQuantizer
from ai_edge_torch.quantize.quant_config import QuantConfig

from modules.model import XFeatModel


xfeat = XFeatModel()
sample_args = (torch.randn(1,3,480,640),)

pt2e_quantizer = PT2EQuantizer().set_global(
    get_symmetric_quantization_config(is_per_channel=True, is_dynamic=True)
)

pt2e_torch_model = capture_pre_autograd_graph(xfeat, sample_args)
pt2e_torch_model = prepare_pt2e(pt2e_torch_model, pt2e_quantizer)

# Run the prepared model with sample input data to ensure that internal observers are populated with correct values
pt2e_torch_model(*sample_args)

# Convert the prepared model to a quantized model
pt2e_torch_model = convert_pt2e(pt2e_torch_model, fold_quantize=False)

# Convert to an ai_edge_torch model
pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer))
```

my error:
```sh
Traceback (most recent call last):
  File "xxxxxxx/git/accelerated_features/test.py", line 30, in <module>
    pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 254, in convert
    return Converter().convert(
           ^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 169, in convert
    return conversion.convert_signatures(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 138, in convert_signatures
    tflite_model = lowertools.exported_programs_to_tflite(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 66, in exported_programs_to_tflite
    bundles: list[utils.MlirBundle] = [
                                      ^
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 67, in <listcomp>
    utils.exported_program_to_mlir(exported, sig.flat_args)
  File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/torch_xla_utils.py", line 70, in exported_program_to_mlir
    return stablehlo.exported_program_to_stablehlo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/xxxxxxx/miniconda3/envs/xfeat/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 626, in exported_program_to_stablehlo
    bundle = _exported_program_to_stablehlo_bundle(exported_model, options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxxxxxx/miniconda3/envs/xfeat/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 378, in _exported_program_to_stablehlo_bundle
    raise RuntimeError(message)
RuntimeError: This model contains ops not capturable by Pytorch/XLA: aten::unfold_copy
```

Am I doing something differently? Which commit for AI-Edge-Torch are you using? Thanks.

**Comment by shubhamgupto** [comment]
> Hi @shubhamgupto, It looks like you're inferencing... were you able to convert successfully? I actually couldn't convert:
> 
> my code:
> 
> ```python
> import torch
> from torch.ao.quantization.quantize_pt2e import prepare_pt2e, convert_pt2e
> from torch._export import capture_pre_autograd_graph
> 
> import ai_edge_torch
> from ai_edge_torch.quantize.pt2e_quantizer import get_symmetric_quantization_config
> from ai_edge_torch.quantize.pt2e_quantizer import PT2EQuantizer
> from ai_edge_torch.quantize.quant_config import QuantConfig
> 
> from modules.model import XFeatModel
> 
> 
> xfeat = XFeatModel()
> sample_args = (torch.randn(1,3,480,640),)
> 
> pt2e_quantizer = PT2EQuantizer().set_global(
>     get_symmetric_quantization_config(is_per_channel=True, is_dynamic=True)
> )
> 
> pt2e_torch_model = capture_pre_autograd_graph(xfeat, sample_args)
> pt2e_torch_model = prepare_pt2e(pt2e_torch_model, pt2e_quantizer)
> 
> # Run the prepared model with sample input data to ensure that internal observers are populated with correct values
> pt2e_torch_model(*sample_args)
> 
> # Convert the prepared model to a quantized model
> pt2e_torch_model = convert_pt2e(pt2e_torch_model, fold_quantize=False)
> 
> # Convert to an ai_edge_torch model
> pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer))
> ```
> 
> my error:
> 
> ```shell
> Traceback (most recent call last):
>   File "xxxxxxx/git/accelerated_features/test.py", line 30, in <module>
>     pt2e_drq_model = ai_edge_torch.convert(pt2e_torch_model, sample_args, quant_config=QuantConfig(pt2e_quantizer=pt2e_quantizer))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 254, in convert
>     return Converter().convert(
>            ^^^^^^^^^^^^^^^^^^^^
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/converter.py", line 169, in convert
>     return conversion.convert_signatures(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/_convert/conversion.py", line 138, in convert_signatures
>     tflite_model = lowertools.exported_programs_to_tflite(
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 66, in exported_programs_to_tflite
>     bundles: list[utils.MlirBundle] = [
>                                       ^
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/_shim.py", line 67, in <listcomp>
>     utils.exported_program_to_mlir(exported, sig.flat_args)
>   File "xxxxxxx/git/ai-edge-torch/ai_edge_torch/lowertools/torch_xla_utils.py", line 70, in exported_program_to_mlir
>     return stablehlo.exported_program_to_stablehlo(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/xxxxxxx/miniconda3/envs/xfeat/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 626, in exported_program_to_stablehlo
>     bundle = _exported_program_to_stablehlo_bundle(exported_model, options)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "xxxxxxx/miniconda3/envs/xfeat/lib/python3.11/site-packages/torch_xla/stablehlo.py", line 378, in _exported_program_to_stablehlo_bundle
>     raise RuntimeError(message)
> RuntimeError: This model contains ops not capturable by Pytorch/XLA: aten::unfold_copy
> ```
> 
> Am I doing something differently? Which commit for AI-Edge-Torch are you using? Thanks.

i am using the latest stable release of ai_edge_torch 0.2.0

I was not able to export batchnorm2d so i replaced those layers with identity and conv2d layers and copied over the running mean and other varaible values

**Comment by pkgoogle** [comment]
Hi @shubhamgupto, I'm still unable to reproduce your issue.. can you share your exact code? Both the conversion, inference and modeling? Did you change this file? https://github.com/verlab/accelerated_features/blob/main/modules/model.py
