### ISSUE TITLE
Encounter 'normalizer.cc(52) LOG(INFO) precompiled_charsmap is empty. use identity normalization.' error when running exported models with AI Edge example.

### ISSUE THREAD

**Issue by merronmuche** [google-ai-edge/ai-edge-torch#350]
### Description of the bug:

I am trying to run an exported TFLite model, specifically the Gemma TFLite model. After downloading both tokenizer.model and gemma-1.1-2b-it-cpu-int8.bin from Hugging Face and ran the following command to execute the model  using AI  Edge Example:

```
 bazel run -c opt //ai_edge_torch/generative/examples/cpp:text_generator_main \
    --tflite_model=/home/meron/Downloads/gemma-1.1-2b-it-cpu-int8.bin \
    --sentencepiece_model=/home/meron/Downloads/tokenizer.model \
    --start_token=2 \
    --stop_token=1 \
    --num_threads=16 \
    --prompt="Write an email:" \
    --weight_cache_path=/home/meron/projects/ai-edge-torch/gemma/gemma
```
However, I encountered an error during execution. The command output was as follows:

''' normalizer.cc(52) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Error at ai_edge_torch/generative/examples/cpp/text_generator_main.cc:212'''  

The following is the full output of the command 
[run_error.txt](https://github.com/user-attachments/files/17713646/run_error.txt)

The executable file is the following

[link](https://github.com/google-ai-edge/ai-edge-torch/blob/main/ai_edge_torch/generative/examples/cpp/text_generator_main.cc
)

### Actual vs expected behavior:

Expected:  load the model successfully and generate text based on the prompt provided without errors.
Actual: encountering an error

**Comment by hheydary** [comment]
Greetings,

If I understand correctly, you are downloading the .bin artifact from HuggingFace. Those converted files are NOT meant to be used with `text_generator_main`. If you would like a *tflite* file that works with this script, please use [this](https://github.com/google-ai-edge/ai-edge-torch/blob/main/ai_edge_torch/generative/examples/gemma/convert_gemma2_to_tflite.py) to export your own model from source. 

The .bin files are meant to be used with [MediaPipe](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference).

**Comment by merronmuche** [comment]
Hi @hheydary,
Thank you so much for clarifying! I’ll give that a try.
