### ISSUE TITLE
[TFLite] Conversion support for 3D operators with channels first data format

### ISSUE THREAD

**Issue by pkgoogle** [google-ai-edge/ai-edge-torch#392]
### Description of the bug:

Original Issue: https://github.com/tensorflow/tensorflow/issues/53315
Opening on behalf of @Tessil

Hello,

TensorFlow Lite currently supports the conversion of 2D operators like `tf.keras.layers.Conv2D`, `tf.keras.layers.MaxPool2D`, ... with `data_format="channels_first"` through the insertion of `TRANSPOSE` operators as the TFLite kernels only support the channels last format.

Would it be possible to add something similar for 3D operators like  `tf.keras.layers.Conv3D`, `tf.keras.layers.MaxPool3D`, ... that use `data_format="channels_first"`?

Example script:
```python
import tensorflow as tf

input = tf.keras.Input(shape=[1, 3, 8, 8, 8])
output = tf.keras.layers.Conv3D(
    filters=12,
    kernel_size=(2, 2, 2),
    data_format="channels_first",
    use_bias=False,
)(input)
model = tf.keras.Model(input, output)


converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
```

Conversion error with TF 2.7.0 (note that setting `data_format="channels_last"` works):
```
error: 'tf.Conv3D' op is neither a custom op nor a flex op
error: failed while converting: 'main':
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: Conv3D
Details:
        tf.Conv3D(tensor<?x3x8x8x8xf32>, tensor<2x2x2x3x12xf32>) -> (tensor<?x12x7x7x7xf32>) : {data_format = "NCDHW", device = "", dilations = [1, 1, 1, 1, 1], padding = "VALID", strides = [1, 1, 1, 1, 1]}
```

Thibaut

**Comment by gaikwadrahul8** [comment]
This issue originally reported by @Tessil has been moved to this dedicated repository for [ai-edge-torch](https://github.com/google-ai-edge/ai-edge-torch) to enhance issue tracking and prioritization. To ensure continuity, we have created this new issue on your behalf.

We appreciate your understanding and look forward to your continued involvement.

**Comment by pkgoogle** [comment]
Hi @Tessil, you can achieve this, with this library:

```py
import torch
import torch.nn as nn

import ai_edge_torch


class Conv3DModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv3d = nn.Conv3d(
            in_channels=3,  # Input channels from shape (1, 3, 8, 8, 8)
            out_channels=12,
            kernel_size=(2, 2, 2),
            bias=False,
        )

    def forward(self, x):
        return self.conv3d(x)


model = Conv3DModel()

# Create a dummy input tensor
sample_input = (torch.randn(1, 3, 8, 8, 8),)

edge_model = ai_edge_torch.convert(model.eval(), sample_input)
edge_model.export("3dconv.tflite")
```

Does this resolve your issue?
