### ISSUE TITLE
Trying to run in google colab for TinyLlama tflite_conversion.py

### ISSUE THREAD

**Issue by krishna1870** [google-ai-edge/ai-edge-torch#419]
### Description of the bug:

When i am trying to run in google colab the call is going to main package (local/lib/python-3.10/ai_edge_torch.utilities.__init__.py) instead of local file that i cloned. Actually, __init__.py is empty. So, i am unable to import certain function.How to overcome to this error?

**Comment by pkgoogle** [comment]
Hi @krishna1870, do you have a link to the colab in question? or a gist if you prefer? That will help us understand your issue.
