### ISSUE TITLE
MacOS installation failed

### ISSUE THREAD

**Issue by YuMinHui825** [google-ai-edge/ai-edge-torch#67]
### Description of the bug:

I executed it on macos：
-pip install -r https://github.com/google-ai-edge/ai-edge-torch/releases/download/v0.1.1/requirements.txt

-Looking in links: https://download.pytorch.org/whl/nightly/torch_nightly.html, https://download.pytorch.org/whl/nightly/torch_nightly.html, https://download.pytorch.org/whl/nightly/torch_nightly.html
Ignoring torch_xla: markers 'python_version == "3.11"' don't match your environment
Ignoring torch_xla: markers 'python_version == "3.10"' don't match your environment
ERROR: torch_xla-nightly+20240429-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.

I would like to ask if macOS still does not support the installation of ai-edge-torch?

**Comment by AkiSakurai** [comment]
Unfortunately, PyTorch has discontinued support for x64 macOS.
https://github.com/pytorch/pytorch/issues/114602

**Comment by YuMinHui825** [comment]
这是来自QQ邮箱的自动回复邮件。您好！     邮件我已收到，谢谢。

**Comment by YuMinHui825** [comment]
I know, I'm using an M2 Mac, is it not supported?

**Comment by pkgoogle** [comment]
Hi @YuMinHui825, apologies, but we currently only support what is stated on the repo:

https://github.com/google-ai-edge/ai-edge-torch?tab=readme-ov-file#installation
![image](https://github.com/google-ai-edge/ai-edge-torch/assets/132095473/c42272d9-de64-4f6e-be03-acf3aa091138)

This is independent of PyTorch support for Mac M2's, for that you will have to look at the PyTorch repo. Thanks.

**Comment by YuMinHui825** [comment]
OK, got it. Thanks.

**Comment by pkgoogle** [comment]
Hi @YuMinHui825, if you have no more open items, please feel free to close if your question was answered. Thanks.
