### ISSUE TITLE
Documentation Clarity

### ISSUE THREAD

**Issue by HatmanStack** [google-ai-edge/ai-edge-torch#82]
### Description of the bug:

n/a

### Actual vs expected behavior:

n/a

### Any other information you'd like to share?

Better documentation for this tool is needed. The current guide assumes too much prior knowledge, making it challenging for newcomers. It lacks clear explanations and context, feeling as if written by someone deeply familiar with the tool rather than from a user's perspective.

**Comment by pkgoogle** [comment]
Hi @HatmanStack, thanks for pointing this out. The tool is currently on version 0.1.1 so I expect this to be true for quite awhile. As we move towards version 1.0 this will likely be rectified.

**Comment by HatmanStack** [comment]
I have no doubt, I've seen great results when not using quantized models which I'm sure is a focus and will get better.  The CPU restriction when using torch also made things difficult.  Initially, I had to experiment with different models / loading strategies.  Transformers for instance rather than the stock Pytorch models.  More examples here would be helpful for others.  Keep up the Good Work!
